#! /bin/sh

ARGS=`getopt -q -l "test-name:,log-file:,trs-file:
,color-tests:,expect-failure:,enable-hard-errors:" -o "+" -- $@`

eval set -- "$ARGS;"

while [ "$1" != "--" ]; do shift; done

shift

eval exec $@ $ARGS
