.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH ASONQ 1 "DECEMBER 2013" Linux "User Manuals"
.SH NAME
asonq \- Interactive ASON evaluation
.SH SYNOPSIS
.B asonq
.SH DESCRIPTION
.B asonq
is an interactive shell for evaluating ASON expressions. It supports standard
ASON expressions as well as assignment to variables with the := operator.
.SH COMMANDS
Commands begin with \\ to differentiate them from ASON expressions.
.IP \\\\quit
Exit the 
.B asonq
shell.
.SH AUTHOR
Casey Dahlin <cdahlin@redhat.com>
