.TH ASON_DESTROY 3 "JANUARY 2014" Linux "User Manuals"
.SH NAME
ason_destroy \- Free resources associated with an ason_t value.

.SH SYNOPSIS
.B #include <ason/ason.h>
.sp
.B void ason_destroy(ason_t *a);
.SH DESCRIPTION
.B ason_destroy
releases an
.I ason_t *
and frees associated resources.
.SH SEE ALSO
.BR ason_values (3)
.SH AUTHOR
Casey Dahlin <casey.dahlin@gmail.com>



